### ISSUE TITLE
amd/src/jquery.form.js not declared in thirdpartylibs.xml

### ISSUE THREAD

**Issue by mudrd8mz** [ethz-let/moodle-qtype_sc#3]
All 3rd party libraries must be correctly declared 

https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

**Comment by Clyxz** [comment]
Hi David,
I added the thirdpartylibs.xml file with the new commit. In the near future this library will be removed completely in order to reduce the amount of dependencies to one with just jQuery.
