### ISSUE TITLE
English lang pack should not use Capitalised Strings 

### ISSUE THREAD

**Issue by mudrd8mz** [ethz-let/moodle-qtype_sc#4]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

Strings such as "Single Choice", "General Feedback" should have just the first word capitalised.

**Comment by Clyxz** [comment]
Hi David,
Thank you for the feedback! The mentioned parts are fixed now with the last commit.
However the String "Single Choice" is meant to be exactly the way it is written since this is part of the plugin specification.
